name: CI

on:
    push:
        branches: [main]
    pull_request: {}

jobs:
    test:
        name: Node.js v${{ matrix.nodejs }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [10, 12, 14]
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: ${{ matrix.nodejs }}

            - run: echo "::add-path::$(yarn global bin)"

            - name: Install
              run: |-
                  yarn --frozen-lockfile;

            - name: Compile
              run: yarn build

            - name: Test
              run: yarn jest --coverage --ci

            - name: Report
              if: matrix.nodejs >= 14
              run: bash <(curl -s https://codecov.io/bash);
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
